# Generated by Django 6.0.2 on 2026-06-06 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagramGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('answer', models.CharField(help_text="Yashirin so'z (masalan: VARIABLE)", max_length=64)),
                ('hint', models.CharField(blank=True, help_text='Ixtiyoriy ishora', max_length=255)),
                ('xp', models.PositiveIntegerField(default=10, help_text="To'g'ri yechgani uchun XP")),
                ('difficulty', models.CharField(choices=[('EASY', 'Oson'), ('MEDIUM', "O'rta"), ('HARD', 'Qiyin')], default='EASY', max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('difficulty', models.CharField(choices=[('EASY', 'Oson'), ('MEDIUM', "O'rta"), ('HARD', 'Qiyin')], db_index=True, default='MEDIUM', max_length=10)),
                ('xp', models.PositiveIntegerField(default=15)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizGameQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.quizgame')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuizGameOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='games.quizgamequestion')),
            ],
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('ANAGRAM', 'Anagram'), ('QUIZ', 'Quiz')], db_index=True, max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anagram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.anagramgame')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to='users.studentprofile')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.quizgame')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_profile', 'game_type'], name='games_gamea_student_ed96ca_idx'), models.Index(fields=['student_profile', 'anagram'], name='games_gamea_student_ded0ef_idx'), models.Index(fields=['student_profile', 'quiz'], name='games_gamea_student_bbc46a_idx')],
            },
        ),
    ]
