# Generated by Django 6.0.2 on 2026-06-06 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagramgame',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='anagramgame',
            name='hint',
        ),
        migrations.AlterField(
            model_name='anagramgame',
            name='xp',
            field=models.PositiveIntegerField(default=10, help_text="Barcha so'zlar topilgani uchun XP"),
        ),
        migrations.CreateModel(
            name='AnagramWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(help_text="Yashirin so'z (masalan: VARIABLE)", max_length=64)),
                ('hint', models.CharField(blank=True, help_text='Ixtiyoriy ishora', max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='games.anagramgame')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('game', 'order')},
            },
        ),
    ]
