# Generated by Django 6.0.2 on 2026-03-08 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('book_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('book_pages', models.PositiveIntegerField(blank=True, help_text='Kitob sahifalari soni', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Mavzu tartibi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='academic_gr_name_cd36d2_idx',
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academic.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'order')},
        ),
    ]
