# Generated by Django 6.0.2 on 2026-04-03 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_subject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Material nomi (masalan: Formula list)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Qisqacha izoh')),
                ('file', models.FileField(blank=True, null=True, upload_to='topic_resources/')),
                ('url', models.URLField(blank=True, help_text='Tashqi havola (YouTube, Wikipedia va h.k.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academic.topic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
